- name: Build 3 infrastructure nodes
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
    - name: Server build request
      local_action:
        module: rax
        count: 3
        credentials: ~/ansible/.rax_rc
        name: shane.infra%02d.openstack
        flavor: performance1-8
        image: a1558fdc-3182-4a0f-b48a-aa900a5826c3
        key_name: shane-ansible
        group: openstack
        wait: yes
        state: present
        networks:
          - private
          - public
          - iad-overlay-net
      register: rax

- name: Build two compute nodes
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Server build request
      local_action:
        module: rax
        count: 2
        credentials: ~/ansible/.rax_rc
        name: shane.compute%02d.openstack
        flavor: performance1-4
        image: a1558fdc-3182-4a0f-b48a-aa900a5826c3
        key_name: shane-ansible
        group: openstack
        wait: yes
        state: present
        networks:
          - private
          - public
          - iad-overlay-net
      register: rax

- name: Build logging node
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Server build request
      local_action:
        module: rax
        credentials: ~/ansible/.rax_rc
        name: shane.logging%02d.openstack
        flavor: performance1-4
        image: a1558fdc-3182-4a0f-b48a-aa900a5826c3
        key_name: shane-ansible
        group: openstack
        wait: yes
        state: present
        networks:
          - private
          - public
          - iad-overlay-net
      register: rax

- name: Build cinder node
  hosts: localhost
  gather_facts: False
  tasks:
    - name: Server build request
      local_action:
        module: rax
        credentials: ~/ansible/.rax_rc
        name: shane.cinder%02d.openstack
        flavor: performance1-4
        image: a1558fdc-3182-4a0f-b48a-aa900a5826c3
        key_name: shane-ansible
        group: openstack
        wait: yes
        state: present
        networks:
          - private
          - public
          - iad-overlay-net
      register: rax

- name: Attach CBS volume to cinder node
  gather_facts: False
  hosts: localhost
  tasks:
    - name: Storage volume attach request
      local_action:
        module: rax_cbs_attachments
        credentials: ~/ansible/.rax_rc
        volume: cinder-vol
        server: shane.cinder01.openstack
        device: /dev/xvdd
        region: IAD
        wait: yes
        state: present
      register: my_volume
