---

- name: Create SSH key
  gather_facts: false
  hosts: shane.infra01.openstack
  tasks:
    - name: Create SSH key
      user: name=root generate_ssh_key=yes
      register: sshkey

- name: Fetch .pub key
  gather_facts: false
  hosts: shane.infra01.openstack
  tasks:
    - name: Fetch .pub key
      fetch: src=/root/.ssh/id_rsa.pub dest=/tmp/id_rsa.pub flat=yes

- name: Set up authorized_keys for the root user
  gather_facts: false
  hosts: all
  tasks:
    - name: Set up authorized_keys for the root user
      authorized_key: >
        user=root
        key="{{ lookup('file', '/tmp/id_rsa.pub') }}"
        state=present
