---
#
- name: Run update and upgrade
  apt: upgrade=dist update_cache=yes

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - bridge-utils
    - debootstrap
    - ifenslave
    - ifenslave-2.6
    - lsof
    - lvm2
    - ntp
    - ntpdate
    - openssh-server
    - sudo
    - tcpdump
    - vlan

- name: Enable kernel modules for bonding/vlans
  command: "{{item}}"
  with_items:
    - echo 'bonding' >> /etc/modules
    - echo '8021q' >> /etc/modules 

- name: Copy infra authorized_keys file
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys owner=root group=root mode=0600

- name: Add source for interfaces.d
  shell: echo 'source /etc/network/interfaces.d/*.cfg' >> /etc/network/interfaces

- name: Copy template interfaces file
  copy: src=openstack-interfaces.cfg dest=/etc/network/interfaces.d/openstack-interfaces.cfg mode=0644
