---
#
- name: Run update and upgrade
  apt: upgrade=dist update_cache=yes

- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - bridge-utils
    - debootstrap
    - ifenslave
    - ifenslave-2.6
    - lsof
    - lvm2
    - ntp
    - ntpdate
    - openssh-server
    - sudo
    - tcpdump
    - vlan

- name: Enable kernel modules for bonding/vlans
  copy: src=modules dest=/etc/modules owner=root group=root mode=0644 

- name: Copy infra authorized_keys file
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys owner=root group=root mode=0600

- name: Add source for interfaces.d
  shell: echo 'source /etc/network/interfaces.d/*.cfg' >> /etc/network/interfaces

- name: Copy template interfaces file
  template: src=openstack-interfaces.j2 dest=/etc/network/interfaces.d/openstack-interfaces.cfg mode=0644

- name: Restart servers 
  command: shutdown -r now "Ansible updates triggered"
  async: 0
  poll: 0
  ignore_errors: true

- name: Waiting for servers to come back
  local_action: wait_for host={{ ansible_ssh_host }} port=22 state=started timeout=300
  sudo: false
